name: Terraform + Ansible CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_DO_TOKEN: ${{ secrets.DO_TOKEN }}
      TF_VAR_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      TF_VAR_SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "do_token=${{ secrets.DO_TOKEN }}" -var "ssh_key=${{ secrets.SSH_KEY_NAME }}"
  
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "do_token=${{ secrets.DO_TOKEN }}" -var "ssh_key=${{ secrets.SSH_KEY_NAME }}"

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Ansible Playbook - Install Nginx + SSL
        run: |
          sudo apt update && sudo apt install -y ansible
          ansible-playbook -i inventory.ini install_nginx.yaml

      - name: Print Deployment URL
        run: |
          echo "✅ Deployed! Access the app at: https://uyi.cerebro.ng or http://${{ steps.get_ip.outputs.IP }}"
